pipeline:
  identifier: Build_Cager2808_KhanaDhaba_1715078254135
  name: Build KhanaDhaba
  orgIdentifier: default
  projectIdentifier: SampleHarness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698735122136
        repoName: Cager2808/KhanaDhaba
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    shell: Sh
                    command: echo "Hello From Pipeline"
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
